spring:
  application:
    name: auth
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/govmanage
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
